modLoader="javafml"
loaderVersion="[44,)"
license="All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
modId="trenzalore"
version="${file.jarVersion}"
displayName="Trenzalore"
logoFile="assets/trenzalore/logo.png"
credits="Mikey for the help!"
authors="UnRealDinnerbone"
description='''
This mod adds a few small helpers to provide compatibility with Forge / Fabric.

This mod also adds does a few small tweaks to the game (all configurable)
'''
[[dependencies.trenzalore]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.trenzalore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"
