# Project
mod_version=26.2.0.0
maven_group=com.unrealdinnerbone
mod_name=Trenzalore
mod_author=UnRealDinnerbone
mod_id=trenzalore
curse_id=870210

# Common
minecraft_version=26.2

neo_version=26.2.0.7-beta

fabric_version=0.153.0+26.2
fabric_loader_version=0.19.3

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


